import { Activty, Environment, Material, SneakerDetails, Type } from "./types";

export const Collection: SneakerDetails[] = [
  {
    brand: "adidas",
    model: "Yeezy Boost 350 V2",
    nickname: "Zebra",
    purchaseDate: "Apr 9, 2023",
    purchasePrice: 250,
    retailPrice: 250,
    size: "US 11",
    condition: "deadstock (new)",
    sku: "D5485-612",
    material: [Material.Canvas],
    activities: [Activty.Casual, Activty.Night_Out, Activty.Work],
    environment: Environment.Indoor,
    type: Type.Style,
    timesWorn: 28,
    lastWorn: "Nov 18, 2025",
    thumbnailImageUrl:
      "https://images.stockx.com/360/adidas-Yeezy-Boost-350-V2-Zebra/Images/adidas-Yeezy-Boost-350-V2-Zebra/Lv2/img01.jpg?w=576&q=60&dpr=1&updated_at=1703165447&h=384",
    notes: "These are my favorite shoes ever",
  },
  {
    brand: "Air Jordan",
    model: "Retro 10",
    nickname: "Shadow (2025)",
    purchaseDate: "Nov 19, 2025",
    purchasePrice: 270,
    retailPrice: 215,
    size: "US 10",
    condition: "deadstock (new)",
    sku: "D5485-612",
    material: [Material.Nubuck],
    activities: [Activty.Casual, Activty.Night_Out],
    environment: Environment.Indoor,
    type: Type.Style,
    timesWorn: 0,
    lastWorn: "",
    thumbnailImageUrl:
      "https://images.stockx.com/images/air-jordan-10-retro-shadow-2025.jpg?fit=fill&bg=FFFFFF&w=576&h=384&q=60&dpr=1&trim=color&updated_at=1762213384",
    notes: "These are my favorite shoes ever",
  },
  {
    brand: "ASICS",
    model: "Gel-1130",
    nickname: "Black Pure Silver",
    purchaseDate: "Jan 1, 2025",
    purchasePrice: 95,
    retailPrice: 95,
    size: "US 10",
    condition: "deadstock (new)",
    sku: "D5485-612",
    material: [Material.Mesh],
    activities: [Activty.Casual, Activty.Fitness, Activty.Work],
    environment: Environment.Indoor,
    type: Type.Comfort,
    timesWorn: 1,
    lastWorn: "Nov 18, 2025",
    thumbnailImageUrl:
      "https://images.stockx.com/360/ASICS-Gel-1130-Black-Pure-Silver/Images/ASICS-Gel-1130-Black-Pure-Silver/Lv2/img01.jpg?w=576&q=60&dpr=1&updated_at=1692624365&h=384",
    notes: "These are my favorite shoes ever",
  },
  {
    brand: "New Balance",
    model: "1906R",
    nickname: "Neon Nights",
    purchaseDate: "Sep 19, 2022",
    purchasePrice: 190,
    retailPrice: 150,
    size: "US 10",
    condition: "used",
    sku: "D5485-612",
    material: [Material.Mesh, Material.Leather],
    activities: [Activty.Casual, Activty.Night_Out, Activty.Work],
    environment: Environment.Indoor,
    type: Type.Style,
    timesWorn: 7,
    lastWorn: "Dec 31, 2024",
    thumbnailImageUrl:
      "https://images.stockx.com/360/New-Balance-1906R-Neon-Nights/Images/New-Balance-1906R-Neon-Nights/Lv2/img01.jpg?w=576&q=60&dpr=1&updated_at=1700151662&h=384",
    notes: "These are my favorite shoes ever",
  },
  {
    brand: "Nike",
    model: "Air Force 1 Low",
    nickname: "Supreme White",
    purchaseDate: "Mar 5, 2021",
    purchasePrice: 180,
    retailPrice: 118,
    size: "US 9.5",
    condition: "used",
    sku: "D5485-612",
    material: [Material.Leather],
    activities: [Activty.Casual, Activty.Night_Out, Activty.Work],
    environment: Environment.Indoor,
    type: Type.Style,
    timesWorn: 50,
    lastWorn: "Oct 31, 2025",
    thumbnailImageUrl:
      "https://images.stockx.com/360/Nike-Air-Force-1-Low-Supreme-Box-Logo-White/Images/Nike-Air-Force-1-Low-Supreme-Box-Logo-White/Lv2/img01.jpg?w=576&q=60&dpr=1&updated_at=1692712590&h=384",
    notes: "These are my favorite shoes ever",
  },
  {
    brand: "adidas",
    model: "AE 2",
    nickname: "With Love",
    purchaseDate: "Oct 18, 2025",
    purchasePrice: 130,
    retailPrice: 130,
    size: "US 9.5",
    condition: "deadstock (new)",
    sku: "D5485-612",
    material: [Material.Textile],
    activities: [Activty.Casual],
    environment: Environment.Mixed,
    type: Type.Performance,
    timesWorn: 2,
    lastWorn: "Oct 31, 2025",
    thumbnailImageUrl:
      "https://images.stockx.com/360/adidas-AE-2-With-Love/Images/adidas-AE-2-With-Love/Lv2/img01.jpg?w=576&q=60&dpr=1&updated_at=1757708284&h=384",
    notes: "These are my favorite shoes ever",
  },
];
